version: '2.2'
services:
  cube:
    build: 
      context: .
      dockerfile: df/Dockerfile
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=databricks-jdbc
      - CUBEJS_DB_NAME=
      - CUBEJS_DB_DATABRICKS_CATALOG=
      - CUBEJS_DB_DATABRICKS_URL=
      - CUBEJS_DB_DATABRICKS_TOKEN=
      - CUBEJS_DB_DATABRICKS_ACCEPT_POLICY=true
    volumes:
      - .:/cube/conf